# site.yml
# Main orchestrator
# This playbook will act as entrypoint of the provision

- name: Run common provisioning on master and workers
  hosts:
    - master
    - workers
  become: true
  roles:
    - common
