#!/bin/python
# Script to upload the files generated by Terraform 
# The state's file and other important files, such as Ansible's inventory, 
# will be stored into a S3 bucket

import os, sys, boto3  # type: ignore
from handle_naming import handle_naming

def main():
    cwd = os.getcwd()
    s3 = boto3.client("s3")
    bucket = "terraform-gen-files"
    files = ["terraform.tfstate"]  # Terraform's state need to be uploaded to the bucket no matter its format
    files += [f for f in os.listdir(cwd) if f.endswith('.s3')]  # Exam the directory to obtain the files with .s3 format

    try: 
        for file in files:
            s3.upload_file(file, bucket, file)  
            print(f"info: File '{file}' successfully uploaded to the bucket.")

    except Exception as e:
        sys.stderr.write(f"fatal: Error when trying to upload or rename files: '{e}'\n")
        sys.exit(400)
    
    finally: handle_naming()

if __name__ == '__main__':
    main()
