# worker/tasks/check_member.yml
---
- name: Check if the node is member of the cluster
  ansible.builtin.shell:
    cmd: set -o pipefail && kubectl get-nodes | grep '{{ inventory_hostname }}'
    executable: /bin/bash
  register: worker_is_member
  changed_when: false
