# worker/tasks/main.yml
# Add the worker into the node
---
- name: Check if the node is member of the cluster
  ansible.builtin.import_tasks: check_member.yml
  changed_when: false

- name: Get the authentication tokens
  ansible.builtin.import_tasks: get_tokens.yml
  when: "worker_is_member is not defined or not worker_is_member"
  delegate_to: '{{ worker_cp_hostname }}'

- name: Test the value of the inventory variables
  debug:
    # msg: "The name of the master node is: {{ groups.master[0] }}"
    var: hostvars
  tags:
    - testing
