# common/tasks/update_hosts.yml
# Retrieve hosts file from S3 bucket an copy it to the instances

- name: Update /etc/hosts file
  ansible.builtin.copy:
    src: hosts
    dest: /etc/hosts
    mode: '0644'
