# roles/tasks/init_kubeadm.yml
# Initialize the cluster

- name: Initialize the cluster
  k8s_init_cluster:
    master_ip: '{{ inventory_hostname }}'
    cidr_block: '{{ master_network.cidr }}'
    user: '{{ ansible_user }}'
