# master/tasks/main.yml
# Contents the steps to specific to the master node

- name: Initialize the cluster
  ansible.builtin.import_tasks: init_kubeadm.yml

- name: Download needed plugins
  ansible.builtin.import_tasks: get_plugins.yml
