# worker/vars/main.yml
# Contains variables used on the role
---
# worker_cp_hostname: '{{ hostvars["master"].master_hostname }}'
# worker_cp_port: '{{ hostvars["master"].cluster_port }}'

worker_cp_hostname: k8scp
worker_cp_port: 6443